# Generated by Django 6.0.1 on 2026-01-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_user_id', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='dashboard.artist')),
            ],
            options={
                'unique_together': {('artist', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_track_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('explicit', models.BooleanField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='dashboard.album')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('is_organic', models.BooleanField(blank=True, null=True)),
                ('played_ratio', models.FloatField(blank=True, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.eventtype')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.user')),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='dashboard_e_ts_84a6c0_idx'), models.Index(fields=['user', 'ts'], name='dashboard_e_user_id_1727b6_idx'), models.Index(fields=['track', 'ts'], name='dashboard_e_track_i_a49bce_idx')],
            },
        ),
    ]
