# Generated by Django 6.0.1 on 2026-01-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='dashboard_e_ts_84a6c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='dashboard_e_user_id_1727b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='dashboard_e_track_i_a49bce_idx',
        ),
        migrations.RemoveField(
            model_name='track',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='track',
            name='explicit',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='yandex_track_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='yandex_user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='played_ratio',
        ),
    ]
